### ISSUE TITLE
Horizontal scrollbar would be useful for big tables

### ISSUE THREAD

**Issue by petrana01-bh** [gorules/editor#9]
I am not sure whether it was available or not before, but today I noticed that it is rather difficult to navigate through the big table with a several columns (8+) in no other way than selecting the text and move the cursor to the left/right side.

**Comment by ivanmiletic** [comment]
Hi, would you be able to send a screenshot? Table has both horizontal and vertical scrolls, table cells have only vertical scrolls in text area
